### ISSUE TITLE
PKCS11Token info logs

### ISSUE THREAD

**Issue by vitorcabral94** [xipki/jpkcs11wrapper#1]
Hello,

When I create a new PKCS11Token object, I have info logs from the lib that are unnecessary, like the HSM info logs when we close all sessions.

It's there a way to disable this kind of logs, without disabling all logs in info level? For example, the session handle logs are useful so I want to maintain it, but this ones are not:

[INFO] C_Initialize: (...)
[INFO] verify on PKCS11Module with pin
[INFO] close all sessions on token: (...)

Why print this logs at INFO level and not DEBUG?

Thanks !

**Comment by xipki** [comment]
The logging level is chosen carefully and shall be reasonable. Please implement your own logger and register it like https://github.com/xipki/jpkcs11wrapper/blob/269e62b6874ef8ca3a885a516411d68a81a2d49c/src/test/java/test/pkcs11/wrapper/TestBase.java#L73-L73.
