### ISSUE TITLE
Encryption with ECIES returns CKR_MECHANISM_PARAMS_INVALID

### ISSUE THREAD

**Issue by vitorcabral94** [xipki/jpkcs11wrapper#4]
Hi Lijun,

I'm trying to encrypt data in a Thales HSM using EC Public Key (in this case ECDSA type) with the mechanism ECIES, but I'm receiving the error CKR_MECHANISM_PARAMS_INVALID.

Checking your tests code I didn't find nothing related to this, you don't have any case of encryption using Elliptic Curves keys, and the only PARAMS classe I found related to this is CK_ECDH1_DERIVE_PARAMS, but I'm not sure how to properly use it.

I checked the documentation for the CKM_ECIES mechanism and it says that support ECDSA keys for encryption operation: https://thalesdocs.com/gphsm/luna/7/docs/network/Content/sdk/mechanisms/CKM_ECIES.htm

Also I found this documentation relating to ECIES, but it's extremely vague for me and I can't extract any useful information from it: https://thalesdocs.com/gphsm/luna/7/docs/network/Content/sdk/using/ecies_general.htm

Since you have a lot of experience in this field, can you kindly help me understand how can I solve this, or at least guide me to where I can search inside the jpkcs11wrapper lib for some clues? Other asymmetric keys like RSA are so much easier to understand and use for all kind of operations, EC keys otherwise can be very stressful.

Thank you so much for the support, best regards,
Vítor Cabral

**Comment by xipki** [comment]
Hi Vitor,
sorry for the delayed answer. As defined under https://thalesdocs.com/gphsm/luna/7/docs/network/Content/sdk/using/ecies_general.htm
